### ISSUE TITLE
x and y coordinates mismatched

### ISSUE THREAD

**Issue by goatandsheep** [goatandsheep/overleia#27]
Output locations not precise anymore since January 20th updates. Samples coming soon

**Comment by ChrisCates** [comment]
![image](https://user-images.githubusercontent.com/1561091/118921768-be627d00-b906-11eb-92c5-c3f91c9f35d4.png)

Looks correct with the following config:

```typescript
[
        {
          x: 0,
          y: 0,
          height: 733,
          width: 1303,
        },
        {
          x: 10.3451,
          y: 10.435234,
          height: 250.5434,
          delay: 1,
        },
        {
          x: 78.0982905982906,
          y: 482.1267806267807,
          height: 180.14672364672367,
          width: 320.72364672364677,
          delay: 2,
        },
        {
          x: 400,
          y: 400,
          height: 250,
          delay: 3,
        },
]
```

Using

```
node v14.0.0
npm 6.14.4
```

Could you provide sample configs and tests where it fails?
Maybe add a new commit with the new views in the unit tests.

Also, can migrate it to Mocha Unit Testing for ease of use later.

**Comment by goatandsheep** [comment]
these are the params that failed:

```json
[
        {
          "height": 250,
          "x": 45,
          "y": 88
        },
        {
          "height": 250,
          "x": 766,
          "y": 84
        },
        {
          "height": 250,
          "x": 408,
          "y": 387
        }
      ]
```

I'm going to try just by removing the widths. maybe it's the ratio that's off

**Comment by goatandsheep** [comment]
![image](https://user-images.githubusercontent.com/5570628/119171299-6163e580-ba32-11eb-938a-68ec12a634b9.png)

**Comment by goatandsheep** [comment]
i think it's an issue with the first layer and how it's being padded

**Comment by goatandsheep** [comment]
https://user-images.githubusercontent.com/5570628/119171438-953f0b00-ba32-11eb-9859-3023191b9aa1.mp4
